#开发环境配置文件
env:
  dev-60

server:
  port: 8080
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.102:3306/mall?characterEncoding=utf-8
    username: root
    password: abcd1234@!
    #连接池配置
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      #连接池启动时的初始值
      initial-size: 20
      #最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止
      max-idle: 20
      #最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请
      min-idle: 10
      #最大建立连接等待时间。如果超过此时间将接到异常。设为－1表示无限制
      max-wait-millis: 10
      default-auto-commit: true
      #连接的超时时间，默认为半小时
      min-evictable-idle-time-millis: 1800000
      #失效检查线程运行时间间隔，要小于MySQL默认
      time-between-eviction-runs-millis: 40000
      #检查连接是否有效
      test-while-idle: true
      #检查连接有效性的SQL语句
      validation-query: SELECT 1 FROM dual
#mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  
#配置
version:
  name: 1.0
  note: 正式版


